### ISSUE TITLE
Feeds of Feed Sources empty

### ISSUE THREAD

**Issue by JumpLink** [adrenth/rssfetcher#11]
At first: Thank you very much for this Plugin :)

I have a problem with the Feed of our feed collection, it is empty :(

Currently we have 2 feeds:

- https://freifunk-cuxhaven.de/feeds/communities
- https://freifunk-cuxhaven.de/feeds/freifunk

Both are empty, whether in RSS or Atom.

Here are our current settings:

![auswahl_749](https://user-images.githubusercontent.com/1073989/29210170-72ecf3e4-7e92-11e7-8190-ae0a9d09abe1.png)

![auswahl_748](https://user-images.githubusercontent.com/1073989/29210175-77d25f0c-7e92-11e7-8f5c-5aec9075c230.png)

**Comment by adrenth** [comment]
Thank you for bringing up this issue. I have located the issue and will be fixed in the next release.

**Comment by JumpLink** [comment]
Thank you!
