### ISSUE TITLE
Fetch feed on Edit Source page not working

### ISSUE THREAD

**Issue by JumpLink** [adrenth/rssfetcher#12]
Fetch feed on edit Source Page is not working, if I click on the "Fetch items" button I get the error "AJAX HANDLER 'OnFetch not found:

![auswahl_750](https://user-images.githubusercontent.com/1073989/29210251-edfa50b8-7e92-11e7-9377-eaa86911eb7b.png)

On the overview page it works.

**Comment by adrenth** [comment]
Oops! Thanks for the screenshot. I fixed this issue as well.
