### ISSUE TITLE
Feedburner feeds and some other feeds not being read.

### ISSUE THREAD

**Issue by Ultrapraise** [adrenth/rssfetcher#14]
Hi,
I really enjoy working with your component, thanks for creating and shearing.
I noticed a little issue with reading feeds from certain links and URLs; for example feeds from this URL (http://www.nu.nl/rss/Algemeen) work fine but feeds from https://io9.gizmodo.com/rss, https://feeds.feedburner.com/entrepreneur/latest , https://feed.laravel-news.com/  doesn't seem to work at all.
I tried using feeds i created from feedburner, but it didn't work too.

I thought i should share my observation, maybe someone else may be having the same issue.

I will update this issue when i make progress figuring out what might be causing the problem.

Thanks xoxo

**Comment by Ultrapraise** [comment]
This is fixed with the new update.
Thanks Alwin Drenth.
You rock

**Comment by adrenth** [comment]
I'm happy to hear that you like my plugin. If you haven't already, please leave a rating at octobercms.com and spread the love!

Always happy to help you, so just create an issue if you need help in the future.
