### ISSUE TITLE
An error has occured while fetching the new items from the RSS feed. open_basedir restriction in effect

### ISSUE THREAD

**Issue by cheb60** [adrenth/rssfetcher#16]
**OctoberCMS Buid**
434

**Plugin Version**
2.0.1

**Expected behavior**
When I add a RSS Source and click Fetch the system has to fetch the latest RSS items.

**Actual behavior**
open_basedir_restriction in effect error. Artisan tries to load something from the /usr/local/bin/php directory. It should use the users base directory instead of the root.

**Comment by rajakhoury** [comment]
Yes had this same issue today.

**Comment by adrenth** [comment]
This plugin uses `Artisan::call` to update the RSS feeds. Some hosts have some strict security configuration. I will see if I can fix it with this PHP configuration option enabled.

**Comment by cheb60** [comment]
Thanks for looking into this. Will be glad to hear when there is an update availabke.

**Comment by adrenth** [comment]
Hi Jeroen,

Thanks for your tremendous patience with this issue. This issue is fixed in release 2.1.2.

Please rate this plugin on octobercms.com ;-)
