### ISSUE TITLE
Unable to View OctoberCMS Dashboard - Trying to Get Property of Non-Object Error

### ISSUE THREAD

**Issue by abass** [adrenth/rssfetcher#17]
Unable to view dashboard, popup error saying:

![IMG](https://d3vv6lp55qjaqc.cloudfront.net/items/172h290N0l0K0W243Y1L/Image%202018-05-20%20at%2011.29.56%20PM.png?X-CloudApp-Visitor-Id=51440efb07735d05d70055a92c35f59d&v=19e73ec8)

Not sure what to do here or why it would be popping up. I never actually added the widget 😢

**Comment by adrenth** [comment]
Yikes, thanks for noticing. I pushed a hotfix release for that. Please make sure you install version 2.1.1 which is now available.

**Comment by abass** [comment]
Working now, thank you so much!
