### ISSUE TITLE
Sorting sources by the number of items throws an sql exception

### ISSUE THREAD

**Issue by dzava** [adrenth/rssfetcher#9]
Trying to sort the sources by the number of items produces the following error. 

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count' in 'order clause' (SQL: select `adrenth_rssfetcher_sources`.\* from `adrenth_rssfetcher_sources` order by `count` desc limit 20 offset 0)

[It seems that relations do not support sorting](https://github.com/octobercms/october/issues/596)

**Comment by adrenth** [comment]
Thanks for addressing this issue. This will be fixed in the upcoming release.
